config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :contacts, only: [:new, :create, :index]
  resources :requests
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :pages
  resources :flags
  resources :reviews do
   member do
    get "like", to: "reviews#upvote"
    get "dislike", to: "reviews#downvote"
   end
  end
  
  resources :offers do
   member do
    get "like", to: "offers#upvote"
    get "dislike", to: "offers#downvote"
   end
  end
  
  resources :offers do 
     resources :companies
  end
  
  resources :reviews do 
    resources :companies
    resources :flags
  end 
  
  resources :flags do
    resources :reviews
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
 
  
  resources :users, only: [:show]

  resources :companies do 
  	resources :reviews
  	 collection do 
  	 	get :search #creates new path for the search input
  	  get :autocomplete
     end
    resources :offers
     collection do 
      get :search #creates new path for the search input
     end
    resources :requests
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'companies#index'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tos', to: 'pages#tos'
  get 'privacy', to: 'pages#privacy'
  get 'profile', to: 'users#show'
  get 'testing', to: 'pages#testing'
  get 'faq', to: 'pages#faq'

  match 'users/:id' => 'users#show', via: :get

end

app/views/shared/_footer.html.erb
<!-- Footer -->
<section id="footer">
  <div class="container">
      <div class="row text-center text-xs-center text-sm-left text-md-left">
          <div class="col-xs-12 col-sm-4 col-md-4">
          <% if user_signed_in? -%>
              <h5>Quick links</h5>
              <ul class="list-unstyled quick-links">
                  <li><i class="fa fa-angle-double-right" style="color:white"></i> <%= link_to 'Home', root_path %></li>
                  <li><i class="fa fa-angle-double-right" style="color:white"></i> <%= link_to 'Submit a Company', new_company_path %></li>
                  <li><i class="fa fa-angle-double-right" style="color:white"></i> <%= link_to 'Profile', profile_path %></li>
                  <li><i class="fa fa-angle-double-right" style="color:white"></i> <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
              </ul>
          <% else %>
              <h5>Quick links</h5>
              <ul class="list-unstyled quick-links">
                  <li><i class="fa fa-angle-double-right" style="color:white"></i> <%= link_to 'Home', root_path %></li>
                  <li><i class="fa fa-angle-double-right" style="color:white"></i> <%= link_to 'Submit a Company', new_company_path %></li>
                   <li><i class="fa fa-angle-double-right" style="color:white"></i> <%= link_to 'Sign Up', new_user_registration_path %></li>
                  <li><i class="fa fa-angle-double-right" style="color:white"></i> <%= link_to 'Log In', new_user_session_path %></li>
          <% end %>
          </div>
          <div class="col-xs-12 col-sm-4 col-md-4">
              <h5>Info</h5>
              <ul class="list-unstyled quick-links">
                  <li><i class="fa fa-angle-double-right" style="color:white"></i> <%= link_to 'About', about_path%></li>               
                  <li><i class="fa fa-angle-double-right" style="color:white"></i> <%= link_to 'Privacy and Cookie Policy', privacy_path%></li>
                  <li><i class="fa fa-angle-double-right" style="color:white"></i> <%= link_to 'Terms of Service', tos_path %></li>
                 <li><i class="fa fa-angle-double-right" style="color:white"></i> <%= link_to 'Guidelines/FAQ', faq_path %></li>
              </ul>
          </div>
          <div class="col-xs-12 col-sm-4 col-md-4">
              <h5>Contact Us</h5>
              <ul class="list-unstyled quick-links">
                  <li><i class="fa fa-angle-double-right" style="color:white"></i> <%= link_to 'Send Us A Message', new_contact_path%></li>
              </ul>
          </div>
      </div>
      <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
              <ul class="list-unstyled list-inline social text-center">
                  <li class="list-inline-item"><a href="https://www.facebook.com/pg/relyapply/"><i class="fab fa-facebook-square"></i></a></li>
                  <li class="list-inline-item"><a href="https://www.linkedin.com/company/35539037/"><i class="fab fa-linkedin"></i></i></a></li>
                  <li class="list-inline-item"><a href="https://twitter.com/RelyApply"><i class="fab fa-twitter"></i></a></li> 
                  <li class="list-inline-item"><a href="https://www.instagram.com/relyapply/"><i class="fab fa-instagram"></i></a></li>     
              </ul>
          </div>
          </hr>
      </div>  
      <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
              <p><u><a href="https://www.relyapply.com/">RelyApply</a></u> Copyright © 2019 "RelyApply" and logo are proprietary trademarks of 
                RelyApply, LLC</p>
              <p class="h6">&copy All right Reversed. RelyApply, LLC</a></p>
          </div>
          </hr>
      </div>  
  </div>
</section>
<!-- ./Footer -->

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark " id="navbar">
    <div id="logo" class="navbar-brand"><%= link_to "RelyApply", root_path %></div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample05" aria-controls="navbarsExample05" aria-expanded="true" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarsExample05">
      <% if user_signed_in? -%>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active "><%= link_to 'Home', root_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'About', about_path, class: 'nav-link'  %></li>
          <li class="nav-item"><%= link_to 'Profile', profile_path, class: 'nav-link'  %></li>
          <li class="nav-item"><%= link_to 'Sign out', destroy_user_session_path, :method => :delete, class: 'nav-link'  %></li>
        </ul>
      <% else -%>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><%= link_to 'Home', root_path, class: 'nav-link'  %></li>
          <li class="nav-item"><%= link_to 'About', about_path, class: 'nav-link'  %></li>
          <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'  %></li>
          <li class="nav-item"><%= link_to 'Log In', new_user_session_path, class: 'nav-link'  %></li>
        </ul>
      <% end %>
    <%= link_to 'Submit a Company', new_company_path, :class => "btn btn-primary justify-content-md-around", :id => "submitCompanyPortal" %>
   <div class="divider"/>
   </div>
    <% unless controller_name == 'companies' && action_name == 'index' %>
      <%= form_tag(search_companies_path, method: :get, :class => "form-inline mt-2 mt-md-0", :id => "navbarsExample05") do %>
        <div class="input-group">
          <%= text_field_tag :search,  "",  placeholder: "Search Companies...", class: 'form-control input-lg', id: 'input-field-home', data: { behavior:"autocomplete", autocomplete_source: autocomplete_companies_path } %>
          <div class="input-group-append">
              <%=button_tag( :class => "btn",  id: "navBarSearchButton") do %>
                <i class="fas fa-search"></i>
              <%end %>
          </div>        
        </div>
      <% end %> 
    <% end %>
  </nav>
  <script>  
    $(document).on("page:change", function() {
      $(".navbar .dropdown").hover((function() {
        $(this).find(".dropdown-menu").first().stop(true, true).delay(150).slideDown();
      }), function() {
        $(this).find(".dropdown-menu").first().stop(true, true).delay(50).slideUp();
      });
    });
  </script>
</header>




   