config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :contacts, only: [:new, :create, :index]
  resources :requests
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :pages
  resources :flags
  resources :reviews do
   member do
    get "like", to: "reviews#upvote"
    get "dislike", to: "reviews#downvote"
   end
  end
  
  resources :offers do
   member do
    get "like", to: "offers#upvote"
    get "dislike", to: "offers#downvote"
   end
  end
  
  resources :offers do 
     resources :companies
  end
  
  resources :reviews do 
    resources :companies
    resources :flags
  end 
  
  resources :flags do
    resources :reviews
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
 
  
  resources :users, only: [:show]

  resources :companies do 
  	resources :reviews
  	 collection do 
  	 	get :search #creates new path for the search input
  	  get :autocomplete
     end
    resources :offers
     collection do 
      get :search #creates new path for the search input
     end
    resources :requests
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'companies#index'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tos', to: 'pages#tos'
  get 'privacy', to: 'pages#privacy'
  get 'profile', to: 'users#show'
  get 'testing', to: 'pages#testing'
  get 'faq', to: 'pages#faq'

  match 'users/:id' => 'users#show', via: :get

end

app/models/company.rb
class Company < ApplicationRecord
	extend FriendlyId
    friendly_id :name, use: :slugged
	has_many :reviews
	has_many :requests
	has_many :offers
	validates_presence_of :name, :website
	validates_uniqueness_of :name, :case_sensitive => false
	validates :website, url: true
	
	def self.search(params)
		companies = Company.where("name iLIKE ? or website iLIKE ?", "%#{params[:search]}%", "%#{params[:search]}%") if params[:search].present?
	end

	def company_name
		company.try(:name)
	end

	def company_name=(name)
		self.company = Company.find_by_name(name) if name.present?
	end
	
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy, :ranking]
  before_action :all_companies, only: [:index, :search, :autocomplete]
  before_action :force_json, only: :autocomplete
  before_action :authenticate_user!, except: [:index, :show, :search, :autocomplete]
  load_and_authorize_resource
  
  # GET /companies
  # GET /companies.json
  def index
  end

  def search
    if params[:search].blank?
      @companies = Company.all.paginate(:page => params[:page], :per_page => 5)
    else 
      @companies = Company.search(params).paginate(:page => params[:page], :per_page => 5)
    end
    @search = params[:search] 
  end

  def autocomplete
    @companies = Company.order(:name).where("name Ilike ?","%#{params[:term]}%").limit(5)
    render json: @companies.map(&:name)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show  
    @company = Company.friendly.find(params[:id])
  
  end


  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save && verify_recaptcha(model: @company)
        
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.friendly.find(params[:id])
    end

    def search_params
      params.require(:companies).permit(:search)
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :website)
    end

    def all_companies
      @companies = Company.all
    end 
    
    def force_json
      request.format = :json
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_search_desktop.html.erb
<% content_for :title do %>
 Search | RelyApply
<% end %>

<div class="col-12">
  <%= form_tag(search_companies_path, method: :get, enforce_utf8: false) do %>
    <div class="input-group input-group-lg">
      <%= text_field_tag :search,  "",  placeholder: "Search Companies...", class: 'form-control input-lg', id: 'input-field-home', data: {behavior:"autocomplete", autocomplete_source: autocomplete_companies_path} %>
        <div class="input-group-append">
          <%=button_tag( :class => "btn btn-lg btn-default",  id: "navBarSearchButton") do %>
            <i class="fas fa-search"></i>
          <%end %>
        </div>
    </div>
  <% end %> 
</div><!--Line 5 -->
<p id="notice"><%= notice %></p>
<div class="container-fluid" id="searchContainer">
  <br />
  <h4 style="color:#333333">Results For "<%= @search %>"</h4>
  <div>
    <p style="color:#333333"><I>Can't Find It?</I> <%= link_to 'Submit a Company', new_company_path %> </P>
  </div>
  <div class="page_info" style="color: #333333; display:inline">
    <small><%= page_entries_info @companies%></small>
  </div>
  <% if @companies.size == 0 %>
  <% else %>
  <div class="container">
    <div class="float-right" style="color:#333333;" id="responsivenessOnMobile">
      <p class="float-right">Reponsiveness</p>
    </div>
  </div>
  <br />
  <hr id="searchItem">
  <% end %>
  <% @companies.each do |company| %>    
    <div>   
      <div class="card" id="cardSearchPage" style="border-width: 0px">
        <div style="background-color: white">
          <h2 class="card-text good-review-score float-right" id="searchScore">
            <% if company.reviews.size == 0 and company.offers.size == 0 %> 
            <span class="na-review-score-show" id="responseScoreShowPage">     
             N/A
            </span>  
            <br>
          <% elsif ((Float(company.reviews.where(responsiveness: "Yes").size)/(company.reviews.size) * 100) >= 60) and ((Float(company.offers.where(responsiveness: "Yes").size)/(company.offers.size) * 100) >= 60) and ((company.reviews.size == 5 or company.offers.size == 5) or (company.reviews.size + company.offers.size >=  5)) %>
            <span class="good-review-score-show" id="responseScoreShowPage" style="border-radius: 50% !important;">
              <i class="fas fa-thumbs-up" style="color:white"></i>
            </span>
          <% elsif ((Float(company.reviews.where(responsiveness: "Yes").size)/(company.reviews.size) * 100) < 60) and ((Float(company.offers.where(responsiveness: "Yes").size)/(company.offers.size) * 100) < 60) and ((company.reviews.size == 5 or company.offers.size == 5) or (company.reviews.size + company.offers.size >=  5)) %>
            <span class="bad-review-score-show" id="responseScoreShowPage" style="border-radius: 50% !important;">
              <i class="fas fa-thumbs-down"></i>
            </span>
          <% elsif ((Float(company.reviews.where(responsiveness: "Yes").size)/(company.reviews.size) * 100) >= 60) and ((Float(company.offers.where(responsiveness: "Yes").size)/(company.offers.size) * 100) < 60) and ((company.reviews.size == 5 or company.offers.size == 5) or (company.reviews.size + company.offers.size >=  5)) %>
            <span class="mixed-review-score-show" id="responseScoreShowPage">
              Mixed
            </span>
          <% elsif ((Float(company.reviews.where(responsiveness: "Yes").size)/(company.reviews.size) * 100) < 60) and ((Float(company.offers.where(responsiveness: "Yes").size)/(company.offers.size) * 100) >= 60) and ((company.reviews.size == 5 or company.offers.size == 5) or (company.reviews.size + company.offers.size >=  5)) %>
            <span class="mixed-review-score-show" id="responseScoreShowPage">
              Mixed
            </span>
          <% elsif ((Float(company.reviews.where(responsiveness: "Yes").size)/(company.reviews.size) * 100) < 60) and (company.offers.size == 0 and company.reviews.size == 5) %>
            <span class="bad-review-score-show" id="responseScoreShowPage" style="border-radius: 50% !important;">
              <i class="fas fa-thumbs-down"></i>
            </span>
          <% elsif ((Float(company.reviews.where(responsiveness: "Yes").size)/(company.reviews.size) * 100) > 60) and (company.offers.size == 0 and company.reviews.size == 5) %>
            <span class="good-review-score-show" id="responseScoreShowPage" style="border-radius: 50% !important;">
              <i class="fas fa-thumbs-up"></i>
            </span>
          <% elsif ((Float(company.offers.where(responsiveness: "Yes").size)/(company.offers.size) * 100) < 60) and (company.reviews.size == 0 and company.offers.size == 5) %>
            <span class="bad-review-score-show" id="responseScoreShowPage" style="border-radius: 50% !important;">
               <i class="fas fa-thumbs-down"></i>
            </span>
          <% elsif ((Float(company.offers.where(responsiveness: "Yes").size)/(company.offers.size) * 100) > 60) and (company.reviews.size == 0 and company.offers.size == 5) %>
            <span class="good-review-score-show" id="responseScoreShowPage" style="border-radius: 50% !important;" >
              <i class="fas fa-thumbs-up"></i>
            </span>
          <% else %>
            <span class="na-review-score-show" id="responseScoreShowPage">     
              N/A
            </span>  
          <% end %><!-- Line 42 -->     
          </h2> <!-- /h2 card-text -->   
          <!-- Mobile Score Version-->
          <h2 class="card-title" id="searchCardTitleCompany"><span><%= link_to company.name, company, data: { turbolinks: false }%></span></h2> 
          <% if company.verified == true %>  <!-- Verification Indicator --> 
            <p class="card-title" style="color:#333333" id="searchCardTitle">
              <strong>Verified</strong> <i class="fas fa-check" style="color:green"></i>
            </p>
          <% end %>
          <div id="mobileResponsivenessScore" style="display: none;">
            <% if company.reviews.size == 0 and company.offers.size == 0 %> <!--mobile-->
             <p class="mobile-na-review-score-show" style="border-radius: 10px !important;">
              Responsiveness: N/A
              </p>
            <% elsif ((Float(company.reviews.where(responsiveness: "Yes").size)/(company.reviews.size) * 100) >= 60) and ((Float(company.offers.where(responsiveness: "Yes").size)/(company.offers.size) * 100) >= 60) and ((company.reviews.size == 5 or company.offers.size == 5) or (company.reviews.size + company.offers.size >=  5)) %>
              <p class="mobile-good-review-score-show" style="color:white" id="searchCardTitle">
                Responsiveness: <i class="fas fa-thumbs-up" style="color:white"></i>
              </p>
            <% elsif ((Float(company.reviews.where(responsiveness: "Yes").size)/(company.reviews.size) * 100) < 60) and ((Float(company.offers.where(responsiveness: "Yes").size)/(company.offers.size) * 100) < 60) and ((company.reviews.size == 5 or company.offers.size == 5) or (company.reviews.size + company.offers.size >=  5)) %>
              <p class="mobile-bad-review-score-show" style="color:white" id="searchCardTitle">
                Responsiveness: <i class="fas fa-thumbs-down" style="color:white"></i>
              </p>
            <% elsif ((Float(company.reviews.where(responsiveness: "Yes").size)/(company.reviews.size) * 100) >= 60) and ((Float(company.offers.where(responsiveness: "Yes").size)/(company.offers.size) * 100) < 60) and ((company.reviews.size == 5 or company.offers.size == 5) or (company.reviews.size + company.offers.size >=  5)) %>
             <p class="mobile-mixed-review-score-show" style="color:white" id="searchCardTitle">
               Responsiveness: Mixed
              </p>
            <% elsif ((Float(company.reviews.where(responsiveness: "Yes").size)/(company.reviews.size) * 100) < 60) and ((Float(company.offers.where(responsiveness: "Yes").size)/(company.offers.size) * 100) >= 60) and ((company.reviews.size == 5 or company.offers.size == 5) or (company.reviews.size + company.offers.size >=  5)) %>
               <p class="mobile-mixed-review-score-show" style="color:white" id="searchCardTitle">
                Responsiveness: Mixed
              </p>
            <% elsif ((Float(company.reviews.where(responsiveness: "Yes").size)/(company.reviews.size) * 100) < 60) and (company.offers.size == 0 and company.reviews.size == 5) %>
             <p class="mobile-bad-review-score-show" style="color:white" id="searchCardTitle">
               Responsiveness: <i class="fas fa-thumbs-down" style="color:white"></i>
              </p>
            <% elsif ((Float(company.reviews.where(responsiveness: "Yes").size)/(company.reviews.size) * 100) > 60) and (company.offers.size == 0 and company.reviews.size == 5) %>
              <p class="mobile-good-review-score-show" style="color:white" id="searchCardTitle">
                Responsiveness: <i class="fas fa-thumbs-up" style="color:white"></i>
              </p>
            <% elsif ((Float(company.offers.where(responsiveness: "Yes").size)/(company.offers.size) * 100) < 60) and (company.reviews.size == 0 and company.offers.size == 5) %>
             <p class="mobile-bad-review-score-show" style="color:white" id="searchCardTitle">
               Responsiveness: <i class="fas fa-thumbs-down" style="color:white"></i>
              </p>
            <% elsif ((Float(company.offers.where(responsiveness: "Yes").size)/(company.offers.size) * 100) > 60) and (company.reviews.size == 0 and company.offers.size == 5) %>
              <p class="mobile-good-review-score-show" style="color:white" id="searchCardTitle">
               Responsiveness: <i class="fas fa-thumbs-up" style="color:white"></i>
              </p>
            <% else %>
                <p class="mobile-na-review-score-show" style="color:white" id="searchCardTitle" style="border-radius: 10px !important;">
               Responsiveness: N/A
              </p> 
            <% end %><!-- Line 42 -->     
           </div>
          <p class="card-title" style="color:white" id="searchCardTitle">
            <%= link_to company, data: { turbolinks: false }, :class => "btn btn-primary" do %>
              View Company <i class="fas fa-caret-right"></i> 
            <% end %>
          </p>
        </div><!-- /div with id =searchItem-->
      </div><!--Line 26 -->
      <span><hr id="searchItem"></span>
    </div><!--/div right after company each do --> 
  <% end %><!-- Line 24 --> 
  <br />

  <div class="pagination-wrapper" style="text-align: :center;">
    <div style="text-align: :center;">
      <%= will_paginate @companies, :container => false %>
    </div>
  </div>
</div><!-- Line 5 -->
<br>
<script>
  // executes when HTML-Document is loaded and DOM is ready
  $(document).ready(function() {
    console.log("document is ready");
      $( ".card" ).hover(
      function() {
        $(this).addClass('shadow-lg').css('cursor', 'pointer'); 
      }, function() {
        $(this).removeClass('shadow-lg');
      }
    );
  });
</script>

app/views/companies/_show_company_desktop.html.erb
<div class="container emp-profile">
  <form method="post" id="companyFormInsideMainDiv">
    <div class="row">
          <!-- Omitted Profile Company Picture Section00<>
            <div class="col-md-4">
              Company Profile: Profile Picture 
                <div class="profile-img">
                  <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS52y5aInsxSm31CvHOFHWujqUx_wWTS9iM6s7BAm21oEN_RiGoog" alt=""/>
                  <div class="file btn btn-lg btn-primary">
                    Change Photo
                    <input type="file" name="file"/>
                  </div>
                </div>
            </div>
            -->
      <!-- Company Profile: Name, Website, Rating --> 
      <div class="col-md-6">
        <div class="profile-head">
          <h2 id="companyShowTitle">
            <% if @company.verified == true %> 
               <%= @company.name %> <small><i class="fas fa-check-circle" style="color:green"></i></small>
            <% else %> 
               <%= @company.name %> 
          <% end %> 
          </h2>
          <h6>
            <%= link_to @company.website, "#{@company.website}" %>
          </h6>
        </div>
      </div><!-- Line 21 -->
      <div  class= "col-md-6">
        <h3 class="proile-rating">             
          <% if @company.reviews.size == 0 and @company.offers.size == 0 %> 
            <span class="na-review-score-show" id="responseScoreShowPage">
              Responsiveness: N/A
            </span>  
            <br>
            <small id="notEnoughReviews" style="color:red;">*Not Enough Reviews*</small>
            <br>
          <% elsif ((Float(@company.reviews.where(responsiveness: "Yes").size)/(@company.reviews.size) * 100) >= 60) and ((Float(@company.offers.where(responsiveness: "Yes").size)/(@company.offers.size) * 100) >= 60) and ((@company.reviews.size == 5 or @company.offers.size == 5) or (@company.reviews.size + @company.offers.size >=  5)) %>
            <span class="good-review-score-show" id="responseScoreShowPage">
              Responsiveness: <i class="fas fa-thumbs-up" style="color:white"></i>
            </span>
          <% elsif ((Float(@company.reviews.where(responsiveness: "Yes").size)/(@company.reviews.size) * 100) < 60) and ((Float(@company.offers.where(responsiveness: "Yes").size)/(@company.offers.size) * 100) < 60) and ((@company.reviews.size == 5 or @company.offers.size == 5) or (@company.reviews.size + @company.offers.size >=  5)) %>
            <span class="bad-review-score-show" id="responseScoreShowPage">
              Responsiveness: <i class="fas fa-thumbs-down"></i>
            </span>
          <% elsif ((Float(@company.reviews.where(responsiveness: "Yes").size)/(@company.reviews.size) * 100) >= 60) and ((Float(@company.offers.where(responsiveness: "Yes").size)/(@company.offers.size) * 100) < 60) and ((@company.reviews.size == 5 or @company.offers.size == 5) or (@company.reviews.size + @company.offers.size >=  5)) %>
            <span class="mixed-review-score-show" id="responseScoreShowPage">
              Responsiveness: Mixed
            </span>
          <% elsif ((Float(@company.reviews.where(responsiveness: "Yes").size)/(@company.reviews.size) * 100) < 60) and ((Float(@company.offers.where(responsiveness: "Yes").size)/(@company.offers.size) * 100) >= 60) and ((@company.reviews.size == 5 or @company.offers.size == 5) or (@company.reviews.size + @company.offers.size >= 5)) %>
            <span class="mixed-review-score-show" id="responseScoreShowPage">
              Responsiveness: Mixed
            </span>
          <% elsif ((Float(@company.reviews.where(responsiveness: "Yes").size)/(@company.reviews.size) * 100) < 60) and (@company.offers.size == 0 and @company.reviews.size == 5) %>
            <span class="bad-review-score-show" id="responseScoreShowPage">
              Responsiveness: <i class="fas fa-thumbs-down"></i>
            </span>
          <% elsif ((Float(@company.reviews.where(responsiveness: "Yes").size)/(@company.reviews.size) * 100) > 60) and (@company.offers.size == 0 and @company.reviews.size == 5) %>
            <span class="good-review-score-show" id="responseScoreShowPage">
              Responsiveness: <i class="fas fa-thumbs-up"></i>
            </span>
          <% elsif ((Float(@company.offers.where(responsiveness: "Yes").size)/(@company.offers.size) * 100) < 60) and (@company.reviews.size == 0 and @company.offers.size == 5) %>
            <span class="bad-review-score-show" id="responseScoreShowPage">
              Responsiveness: <i class="fas fa-thumbs-down"></i>
            </span>
          <% elsif ((Float(@company.offers.where(responsiveness: "Yes").size)/(@company.offers.size) * 100) > 60) and (@company.reviews.size == 0 and @company.offers.size == 5) %>
            <span class="good-review-score-show" id="responseScoreShowPage">
              Responsiveness: <i class="fas fa-thumbs-up"></i>
            </span>
          <% else %>
            <span class="na-review-score-show" id="responseScoreShowPage">
              Responsiveness: N/A
            </span>  
            <br>
            <small id="notEnoughReviews" style="color:red;">*Not Enough Reviews*</small>
            <br>
          <% end %><!-- Line 42 -->  
          <br>          
          </h3><!--Line 41 -->  
      </div><!-- Line 40 -->
    </div><!-- Line 7 -->
    <div class="row">
      <div class="col-md-12">
        <!-- Company Navbar --> 
        <div class="profile-head">
          <!--Review Links for Mobile-->
          <br />
        <!-- Company Navbar --> 
        <div class="profile-head">
          <!-- Company Navbar Headers --> 
          <ul class="nav nav-tabs" id="navbarCompanyShow" role="tablist">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Submit a Review</a>
              <div class="dropdown-menu" style="text-align: left; ">
                <p><%= link_to '• Application Review', new_company_review_path(@company), :id=>"dropdownItem" %></p>
                <p><%= link_to '• Interview Review', new_company_offer_path(@company), :id=>"dropdownItem" %></p>
              </div>
            </li>
            <li class="nav-item dropdown" style="text-align: left;">
              <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> Show Reviews (<%=@company.reviews.count + @company.offers.count %>)</a>
              <div class="dropdown-menu">
                <p>
                  <%= link_to  company_reviews_path(@company), :id=>"dropdownItem" do %>
                    • For Applications (<%=@company.reviews.count %>)
                  <% end %>
                </p>
                <p>
                  <%= link_to  company_offers_path(@company), :id=>"dropdownItem" do %>
                    • For Interviews (<%=@company.offers.count %>)
                  <% end %>
                </p>
              </div>
            </li>
          </ul>
        </div><!-- Line 85 -->
        </div><!-- Line 85 -->
        <!--div class="card" id="tableCard"-->
            <!-- Response Times Tables -->    
            <div class= "col-md-12" align="center">
              <h2>Post-Application Responsiveness</h2>
            </div>
            <br />
            <!-- Table A: Response Times Tables -->    
            <div class="col-md-12">
              <table class="table">
                <thead class="bg-primary">
                  <th><strong>After Applying (~)</strong></th>
                  <th><strong># Reported</strong></th>
                </thead>
                <tbody>
                  <tr>
                    <td>Less than a week</td>
                    <td><%= @company.reviews.where(response_time: "Less than a week").size %></td>
                  </tr>
                    <tr>
                    <td>1-2 weeks</td>
                    <td><%= @company.reviews.where(response_time: "1-2 weeks").size %></td>
                  </tr>
                  <tr>
                    <td>2-3 weeks</td>
                    <td><%= @company.reviews.where(response_time: "2-3 weeks").size %></td>
                  </tr>
                   <tr>
                    <td>3-4 weeks</td>
                    <td><%= @company.reviews.where(response_time: "3-4 weeks").size %></td>
                  </tr>
                  <tr>
                    <td>Not within a month</td>
                    <td><%= @company.reviews.where(response_time: "Not within a month").size %></td>
                  </tr>
                  <tr class="bg-primary" style="color:white">
                    <td>Average:</td>
                    <td> 
                      <% if @company.reviews.size == 0  %> 
                        n/a
                      <% else %>
                        <%= render 'average_response', company: @company %>
                      <% end %>
                    </td>
                  </tr>
                  <tr class="bg-primary" style="color:white">
                    <td>Average Satisfaction:</td>
                    <td> 
                      <% if @company.reviews.size == 0 %> 
                        n/a
                      <% else %>
                        <%= number_to_percentage((@company.reviews.where(responsiveness: "Yes").count.to_f) / (@company.reviews.count.to_f)* 100, precision:0)%>
                      <% end %>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div><!--Line 123 -->
            <br />
            <!-- Table B: Post-Interview Response Times -->  
            <div class= "col-md-12" align="center">
              <h2>Post-Interview Responsiveness</h2>
            </div>
            <br />
            <div class="col-md-12">
              <table class="table">
                <thead class="bg-secondary">
                  <th><strong>After Interviewing</strong></th>
                  <th><strong># Reported</strong></th>
                </thead>
                <tbody>
                  <tr>
                    <td>Less than a week</td>
                    <td><%= @company.offers.where(response_time: "Less than a week").size %></td>
                  </tr>
                  <tr>
                    <td>1-2 weeks</td>
                    <td><%= @company.offers.where(response_time: "1-2 weeks").size %></td>
                  </tr>
                  <tr>
                    <td>2-3 weeks</td>
                    <td><%= @company.offers.where(response_time: "2-3 weeks").size %></td>
                  </tr>
                    <tr>
                    <td>3-4 weeks</td>
                    <td><%= @company.offers.where(response_time: "3-4 weeks").size %></td>
                  </tr>
                  <tr>
                    <td>Not within a month</td>
                    <td><%= @company.offers.where(response_time: "Not within a month").size %></td>
                  </tr>
                  <tr class="bg-secondary" style="color:white">
                    <td>Average:</td>
                    <td> 
                      <% if @company.offers.size == 0 %> 
                        n/a
                      <% else %>
                        <%= render 'post_interview_average_response', company: @company %>
                      <% end %>
                    </td>
                  </tr>
                  <tr class="bg-secondary" style="color:white">
                    <td>Average Satisfaction:</td>
                    <td> 
                      <% if @company.offers.size == 0 %> 
                        n/a
                      <% else %>
                         <%= number_to_percentage((@company.offers.where(responsiveness: "Yes").count.to_f) / (@company.offers.count.to_f)* 100, precision:0)%>
                      <% end %>
                    </td>
                  </tr>                                 
                </tbody>
              </table><!-- Line 183 -->
            </div><!-- Line 182 -->
        <!--/div--> <!--for the tables -->
        <br />
        <div div align="center">
          <%= link_to 'Profile Information Incorrect?', new_company_request_path(@company), :class => "btn btn-info", :align => "center"%>
              <br />
              <br />
        </div>
        <div align="center">
              <a class="btn btn-info" data-toggle="collapse" href="#collapseDislaimer" role="button" aria-expanded="false" aria-controls="collapseDislaimer">
                Disclaimer
              </a>
              <div class="collapse" id="collapseDislaimer">
                <div class="text-left">
                  <div class="alert alert-info" role="alert">
                    <ul>
                      <li>The information above is based on what users have submitted in their reviews.</li>
                      <li>Their opinions and the information shown on the information above are based on what they felt was a meaningful response/follow-up after an application or an interview. </li>
                    </ul>
                  </div><!--alert-alert-info-->
              </div>
        </div>
        </div>
      </div><!-- Line 83 -->
    </div><!-- Line 7 -->     
  </form><!-- Line 6 -->     
</div><!-- Line 5 -->     











































     

app/views/companies/edit.html.erb
<% content_for :title do %>
  Edit Company | RelyApply
<% end %>

<h1>Editing Company</h1>
<%= render 'form', company: @company %>

app/views/companies/index.html.erb
<% content_for :title do %>
      RelyApply
<% end %>

<% if mobile_device == ("mobile" or "tablet") %>
  <%= render 'index_mobile'%>
<% else %>
  <%= render 'index_desktop'%>
<% end %>