config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :contacts, only: [:new, :create, :index]
  resources :requests
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :pages
  resources :flags
  resources :reviews do
   member do
    get "like", to: "reviews#upvote"
    get "dislike", to: "reviews#downvote"
   end
  end
  
  resources :offers do
   member do
    get "like", to: "offers#upvote"
    get "dislike", to: "offers#downvote"
   end
  end
  
  resources :offers do 
     resources :companies
  end
  
  resources :reviews do 
    resources :companies
    resources :flags
  end 
  
  resources :flags do
    resources :reviews
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
 
  
  resources :users, only: [:show]

  resources :companies do 
  	resources :reviews
  	 collection do 
  	 	get :search #creates new path for the search input
  	  get :autocomplete
     end
    resources :offers
     collection do 
      get :search #creates new path for the search input
     end
    resources :requests
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'companies#index'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tos', to: 'pages#tos'
  get 'privacy', to: 'pages#privacy'
  get 'profile', to: 'users#show'
  get 'testing', to: 'pages#testing'
  get 'faq', to: 'pages#faq'

  match 'users/:id' => 'users#show', via: :get

end

app/models/offer.rb
class Offer < ApplicationRecord
  default_scope { order(created_at: :desc) }
  belongs_to :user
  belongs_to :company, counter_cache: true
  acts_as_votable
  geocoded_by :address
  after_validation :geocode, :if => :address_changed?
  scope :latest, -> { where(created_at: 60.days.ago..DateTime.now.end_of_day) }
  validates_presence_of :response_time, :responsiveness
  #validates :company_id, uniqueness: { scope: :user_id, message: "Post-Interview Review has already been submitted by you. You can still submit a Post-Application Review if you have not done so already." }
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :company_friendly_params, only: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
   before_action :limit_review, only: [:new, :create]

  # GET /offers
  # GET /offers.json
  def index
     @offers = Offer.where(company_id: params[:company_id]) 
    if params[:search].present?
      @q = @company.offers.near(params[:search], 200, :order => 'distance' ).ransack(params[:q])
      @offers = @q.result(:distinct => true)
    else 
      @q = @company.offers.ransack(params[:q])
      @offers = @q.result(:distinct => true)
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
  end

  # GET /offers/new
  def new
    @offer = Offer.new
  end

  # GET /offers/1/edit
  def edit
  end

  # POST /offers
  # POST /offers.json
  def create
    @offer = @company.offers.new(offer_params)
    @offer.user = current_user

    respond_to do |format|
      if @offer.save
        format.html { redirect_to @company, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @offer }
      else
        format.html { render :new }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offers/1
  # PATCH/PUT /offers/1.json
  def update
    respond_to do |format|
      if @offer.update(offer_params)
        format.html { redirect_to @offer.user, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @offer }
      else
        format.html { render :edit }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def upvote
   if !current_user.liked? @offer
      @offer.upvote_by current_user
    elsif current_user.liked? @offer
      @offer.unliked_by current_user
    end
    #redirect_back fallback_location: root_path
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path}
      format.json { render json: { count: @offer.upvoted_count } }
      format.js { render layout: false }
    end
  end

  def downvote 
    if !current_user.disliked? @offer
      @offer.downvote_by current_user
    elsif current_user.disliked? @offer
      @offer.undisliked_by current_user
    end
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render json: { count: @offer.downvoted_count } }
      format.js { render layout: false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_offer
      @offer = Offer.find(params[:id].to_i)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def offer_params
      params.require(:offer).permit(:offer_id, :user_id, :company_id, :position, :employment_type, :responsiveness, :experience, :response_time, :address, :latitude, :longitude, :street_number, :locality, :route, :offer, :administrative_area_level_1, :country, :postal_code)
    end

    def company_friendly_params
       @company = Company.friendly.find(params[:company_id])
    end 

    def limit_review
      user_offer_review = current_user.company_interview_review(@company)

      if user_offer_review.present?
        redirect_back fallback_location: root_path,  alert: "You have already submitted a post-interview review to this company. You can resubmit a new review to this company every quarter of the year." unless current_user.admin?
      end
    end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_offer_index_desktop.html.erb
<div class="container emp-profile">
  <div class="well" id="wellProfileForReviewIndex">
    <div id= "headerProfileForReviewIndex">  
      <h3><%=@company.name%>'s</strong> Interview Reviews</h3>
    </div>
  </div><!-- div class="well" id="wellProfileForReviewIndex"-->
  <p>Want to add a review? Go back to <%= link_to @company.name, company_path(@company), method: :get %>'s profile and click "Submit Review"</p>
  <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Reminder!
  </a>
    <div class="collapse" id="collapseExample">
      <div class="text-left">
        <div class="alert alert-info" role="alert">
          <ul>
            <li><h6>The information below is based on what users have submitted in their reviews</li>
            <li><h6>Their opinions are based on what they felt was a meaningful response after an application or an interview</h6></li>
            <li><h6>If you don't hear back within a reasonable time frame relative to the other reviews, it is highly suggested you do a follow-up or assume you didn't qualify for the job.</h6></li>
          </ul>
        </div>
      </div>
    </div>
    <hr id="reviewIndexHr">
    <div class="container-fluid">
      <%= search_form_for @q, url: company_offers_path(params[:company_id]) do |f| %> 
        <div class="row">
          <h4 class="col"><strong>Filter & Search</strong></h4>
        </div>
        <div class="row">
          <div class="col-sm">
            <%= f.label :response_time_eq, "Response Time: " %>
            <%= f.select :response_time_eq, options_for_select([["Around less than a week","Around less than a week"],
                ["Around 1-2 weeks","Around 1-2 weeks"],
                ["Around 2-3 weeks","Around 2-3 weeks"],
                ["Around 3-4 weeks","Around 3-4 weeks"],
                ["Not within a month","Not within a month"]], @q.response_time_eq), prompt: '--Select--' %>
          </div>
          <div class="col-sm">
            <%= f.label :position, "Position:" %>
            <%= h f.search_field :position_cont, :placeholder => 'Search Position'%>
          </div>
        </div>
        <div class="row">
          <div class="col-sm">
            <%= f.label :responsiveness_eq, "Applicant Satisfied: " %>
            <%= f.select :responsiveness_eq, options_for_select([
              ["Yes","Yes"],
              ["No","No"]
              ] , @q.responsiveness_eq), prompt: '--Select--'   %>
          </div>
          <div class="col-sm">
            <%= f.label :employment_type_eq, "Employment Type: " %>
            <%= f.select :employment_type_eq, options_for_select([
              ["Full-Time","Full-Time"],
              ["Part-Time","Part-Time"],
              ["Intern","Intern"],
              ["Temporary","Temporary"],
              ["Contractor","Contractor"]
              ] , @q.employment_type_eq), prompt: '--Select--'  %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm">
           <%= f.label :experience, "Experience: " %>
           <%= f.select :experience, options_for_select([["Equal or Greater","Equal or Greater"], ["Moderately less experience","Moderately less experience"], ["Little to no experience","Little to no experience"]], @q.experience), prompt: '--Select--' %>
          </div>
          <div class="col-sm">
            <%= f.label :Location, "Location: " %>
            <%= h text_field_tag :search, params[:search], :placeholder => '[City, State] or Zip Code'%>
          </div>
        </div>
          <div class="row">
          <div class="col-sm">
           <%= f.label :offer, "Job Offered: " %>
           <%= f.select :offer, options_for_select([["Yes","Yes"], ["No","No"]], @q.offer), prompt: '--Select--' %>
          </div>
        </div>
        <br />
        <div colspan="1" align="center">
          <%= f.submit :class => "btn btn-primary" %>  <a href="<%=company_offers_path%>" class="btn btn-primary" color="black">Clear filters</a>
        <div>
      <% end %>
    </div>
  </div>
  <hr id="reviewIndexHr">
  <div>
    <h2><strong>Total Interview Reviews: <%= @company.offers.size %></strong></h2>
      <div class="text-left" colspan="1" style="display: inline">  
          <strong>Sort By: </strong>
      </div>
      <div class="text-left"  style="display: inline">
      <%= sort_link(@q, :created_at, default_order: :asc) do %>
        <strong>Date</strong>
      <% end %>
      </div> 
      <div class="text-left" colspan="1" style="display: inline">  
          <strong>|</strong>
      </div> 
      <div class="text-right" colspan="1" style="display: inline" >
        <%= sort_link(@q, :cached_votes_up, default_order: :desc) do %>
          <strong>Likes</strong>
        <% end %>
      </div>    
  </div>
  <% @offers.each do |offer| %>
    <div class="card border-secondary mb-3" id="reviewsIndexCard">
      <div class="card-header" id="reviewsIndexCardHeader">
        <h3>
          Interview Follow-up Response Time: <%= offer.response_time %>
        </h3>
      </div>
      <div class="card-body" id="cardBodyText">
        <p style="color:grey" ><I>Submitted: <%= offer.created_at.strftime("%B %d, %Y") %></I></p>
        <h4><strong>Responsiveness</strong></h4>
        <div class="row"><!--first row of card-->
          <div class="col-md-6">
            <p><strong>Were you satisfied with their level of responsiveness?</strong></p>
          </div>
           <div class="col-md-6">
            <p><%= offer.responsiveness %></p>
          </div>
        </div>
        <hr>
        <h4><strong>Application Details</strong></h4>
        <div class="row"><!--first row of card-->
          <div class="col-md-6">
            <% if offer.position.blank? %> 
              <p><strong>Position:</strong> n/a</p>
            <% else %>
              <p><strong>Position:</strong> <%= offer.position %></p>
            <% end %>
          </div>
          <div class="col-md-6">
            <% if offer.employment_type.blank? %> 
              <p><strong>Employment Type:</strong> n/a </p>
            <% else %>
              <p><strong>Employment Type:</strong> <%= offer.employment_type %></p>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <% if offer.experience.blank? %> 
              <p><strong>Experience Relative to Job Requirement:</strong> n/a </p>
            <% else %>
              <p><strong>Experience Relative to Job Requirement:</strong> <%= offer.experience %> </p>
            <% end %>
          </div>
           <div class="col-md-6">
            <% if offer.offer.blank? %> 
              <p><strong>Did you get an offer? </strong> n/a </p>
            <% else %>
              <p><strong>Did you get an offer? </strong> <%= offer.offer %> </p>
            <% end %>
          </div>
        </div>
        <div class="row"><!--second row of card-->
           <div class="col-md-6">
            <% if offer.address.blank? %> 
             <p><strong>Location:</strong> n/a</p>
            <% else %>
              <p><strong>Location:</strong> <%= offer.address.chomp(', USA') %></p>
           <% end %>
          </div>
        </div>
        <div class="vote-count bind-<%= offer.id %>" style="text-align: center"> <!--links to likes and dislikes -->
          <% if user_signed_in? %>
            <%= link_to like_offer_path(offer),:remote => true, method: :get, class: "vpos", id: "thumbs" do %>
              <button class="btn btn-success">
                <i class="fas fa-thumbs-up" style="color:white"></i>
                <span class="vcount-<%= offer.id %>" style="color:white"> (<%= offer.get_upvotes.size %>)</span>
              </button>
            <% end %>
            <%= link_to dislike_offer_path(offer),:remote => true, method: :get, class: "vpos", id: "thumbs" do %>
                <button class="btn btn-danger">
                  <i class="fas fa-thumbs-down" style="color:white"></i>
                  <span class="ncount-<%= offer.id %>" style="color:white"> (<%= offer.get_downvotes.size %>)</span>
                </button>
            <% end %>
         <% else %>
          <div colspan="1" style="text-align: center"> <!--links to likes and dislikes -->
              <%= link_to new_user_session_path, data: { confirm: "Please Log In to Vote" } do %>
                <button class="btn btn-success">
                  <i class="fas fa-thumbs-up" style="color:white"></i>
                  <span class="vcount-<%= offer.id %>" style="color:white"> (<%= offer.get_upvotes.size %>)</span>
                </button>
              <% end %>
              <%= link_to new_user_session_path, data: { confirm: "Please Log In to Vote" } do %>
                <button class="btn btn-danger">
                  <i class="fas fa-thumbs-down" style="color:white"></i>
                  <span class="ncount-<%= offer.id %>" style="color:white"> (<%= offer.get_downvotes.size %>)</span>
                </button>
              <% end %>
               <div align="center">
    </div>
        <% end %>
        </div><!--close div for to likes and dislikes -->
      </div><!--div close card body-->
    </div> <!--div class="card border-secondary mb-3" id="reviewsIndexCard"-->
    <hr>   
  <% end %>
</div><!--div class="container emp-profile"-->
</div>

app/views/offers/_offer_index_mobile.html.erb
<div style="background-color: white; padding: 10px;">
  <div class="well" id="wellProfileForReviewIndex">
    <div id= "headerProfileForReviewIndex">  
      <h3><%=@company.name%>'s</strong> Interview Reviews</h3>
    </div>
  </div><!-- div class="well" id="wellProfileForReviewIndex"-->
  <p>Want to add a review? Go back to <%= link_to @company.name, company_path(@company), method: :get %>'s profile and click "Submit Review"</p>
  <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Reminder!
  </a>
  <div class="collapse" id="collapseExample">
    <div class="text-left">
      <div class="alert alert-info" role="alert">
        <ul>
          <li><h6>The information below is based on what users have submitted in their reviews</li>
          <li><h6>Their opinions are based on what they felt was a meaningful response after an application or an interview</h6></li>
          <li><h6>If you don't hear back within a reasonable time frame relative to the other reviews, it is highly suggested you do a follow-up or assume you didn't qualify for the job.</h6></li>
        </ul>
      </div>
    </div>
  </div>
  <hr id="reviewIndexHr">
  <%= search_form_for @q, url: company_offers_path(params[:company_id]) do |f| %> 
  <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseSearch" aria-expanded="false" aria-controls="collapseSearch" style="width: 100%;">
   Filter & Search
  </button>
  <div class="collapse" id="collapseSearch">
    <br />
    <div class="row">
      <div class="col-sm">
        <%= f.label :response_time_eq, "Response Time: " %>
        <%= f.select :response_time_eq, options_for_select([["Around less than a week","Around less than a week"],
            ["Around 1-2 weeks","Around 1-2 weeks"],
            ["Around 2-3 weeks","Around 2-3 weeks"],
            ["Around 3-4 weeks","Around 3-4 weeks"],
            ["Not within a month","Not within a month"]], @q.response_time_eq), prompt: '--Select--' %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm">
        <%= f.label :responsiveness_eq, "Applicant Satisfied: " %>
        <%= f.select :responsiveness_eq, options_for_select([
          ["Yes","Yes"],
          ["No","No"]
          ] , @q.responsiveness_eq), prompt: '--Select--'   %>
      </div>
      <div class="col-sm">
        <%= f.label :employment_type_eq, "Employment Type: " %>
        <%= f.select :employment_type_eq, options_for_select([
          ["Full-Time","Full-Time"],
          ["Part-Time","Part-Time"],
          ["Intern","Intern"],
          ["Temporary","Temporary"],
          ["Contractor","Contractor"]
          ] , @q.employment_type_eq), prompt: '--Select--'  %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm">
       <%= f.label :experience, "Experience: " %>
       <%= f.select :experience, options_for_select([["Equal or Greater","Equal or Greater"], ["Little to no experience","Little to no experience"], ["Moderately less experience","Moderately less experience"]], @q.experience), prompt: '--Select--' %>
      </div>
      <div class="col-sm">
           <%= f.label :offer, "Job Offered: " %>
           <%= f.select :offer, options_for_select([["Yes","Yes"], ["No","No"]], @q.offer), prompt: '--Select--' %>
      </div>
    </div>
      <div class="row">
       <div class="col-sm">
        <%= f.label :Location, "Location: " %>
        <%= h text_field_tag :search, params[:search], :placeholder => '[City, State] or Zip Code', :class => 'form-control'%>
      </div>
    </div>
    <div class="row">
      <div class="col-sm">
        <%= f.label :position, "Position:" %>
        <%= h f.search_field :position_cont, :placeholder => 'Search Position', :class => 'form-control'%>
      </div>
    </div>
    <br />
    <div colspan="1" align="center">
          <%= f.submit :class => "btn btn-primary" %>  <a href="<%=company_offers_path%>" class="btn btn-primary" color="black">Clear filters</a>
    </div>
    <% end %>
  </div><!--div class="collapse" id="collapseSearch"-->
  <hr id="reviewIndexHr"><!--search section ends here -->
  <div>
    <h2><strong>Total Interview Reviews: <%= @company.offers.size %></strong></h2>
      <div class="text-left" colspan="1" style="display: inline">  
          <strong>Sort By: </strong>
      </div>
      <div class="text-left"  style="display: inline">
      <%= sort_link(@q, :created_at, default_order: :asc) do %>
        <strong>Date</strong>
      <% end %>
      </div> 
      <div class="text-left" colspan="1" style="display: inline">  
          <strong>|</strong>
      </div> 
      <div class="text-right" colspan="1" style="display: inline" >
        <%= sort_link(@q, :cached_votes_up, default_order: :desc) do %>
          <strong>Likes</strong>
        <% end %>
      </div>    
  </div>
  <% @offers.each do |offer| %>
    <div>
      <div class="card-header" id="reviewsIndexCardHeader">
         <h5 style="color:white;">
          Interview Response Time: <%= offer.response_time %>
        </h5>
      </div>
      <div class="card-body" id="cardBodyText" style="padding-left: 5px; border: 1px grey solid; width: 100%;">
        <p style="color:grey" ><I>Submitted: <%= offer.created_at.strftime("%B %d, %Y") %></I></p>
        <h4><strong>Responsiveness</strong></h4>
        <div class="row"><!--first row of card-->
          <div class="col-md-6">
            <p><strong>Were you satisfied with their level of responsiveness?</strong></p>
          </div>
           <div class="col-md-6">
            <p><%= offer.responsiveness %></p>
          </div>
        </div>
        <hr>
        <h4><strong>Application Details</strong></h4>
        <div class="row"><!--first row of card-->
          <div class="col-md-6">
            <% if offer.position.blank? %> 
              <p><strong>Position:</strong> n/a</p>
            <% else %>
              <p><strong>Position:</strong> <%= offer.position %></p>
            <% end %>
          </div>
          <div class="col-md-6">
            <% if offer.employment_type.blank? %> 
              <p><strong>Employment Type:</strong> n/a </p>
            <% else %>
              <p><strong>Employment Type:</strong> <%= offer.employment_type %></p>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <% if offer.experience.blank? %> 
              <p><strong>Experience Relative to Job Requirement:</strong> n/a </p>
            <% else %>
              <p><strong>Experience Relative to Job Requirement:</strong> <%= offer.experience %> </p>
            <% end %>
          </div>
           <div class="col-md-6">
            <% if offer.offer.blank? %> 
              <p><strong>Did you get an offer? </strong> n/a </p>
            <% else %>
              <p><strong>Did you get an offer? </strong> <%= offer.offer %> </p>
            <% end %>
          </div>
        </div>
        <div class="row"><!--second row of card-->
           <div class="col-md-6">
            <% if offer.address.blank? %> 
             <p><strong>Location:</strong> n/a</p>
            <% else %>
              <p><strong>Location:</strong> <%= offer.address.chomp(', USA') %></p>
           <% end %>
          </div>
        </div>
        <div class="vote-count bind-<%= offer.id %>" style="text-align: center"> <!--links to likes and dislikes -->
          <% if user_signed_in? %>
            <%= link_to like_offer_path(offer),:remote => true, method: :get, class: "vpos", id: "thumbs" do %>
              <button class="btn btn-success">
                <i class="fas fa-thumbs-up" style="color:white"></i>
                <span class="vcount-<%= offer.id %>" style="color:white"> (<%= offer.get_upvotes.size %>)</span>
              </button>
            <% end %>
            <%= link_to dislike_offer_path(offer),:remote => true, method: :get, class: "vpos", id: "thumbs" do %>
                <button class="btn btn-danger">
                  <i class="fas fa-thumbs-down" style="color:white"></i>
                  <span class="ncount-<%= offer.id %>" style="color:white"> (<%= offer.get_downvotes.size %>)</span>
                </button>
            <% end %>
         <% else %>
          <div colspan="1" style="text-align: center"> <!--links to likes and dislikes -->
              <%= link_to new_user_session_path, data: { confirm: "Please Log In to Vote" } do %>
                <button class="btn btn-success">
                  <i class="fas fa-thumbs-up" style="color:white"></i>
                  <span class="vcount-<%= offer.id %>" style="color:white"> (<%= offer.get_upvotes.size %>)</span>
                </button>
              <% end %>
              <%= link_to new_user_session_path, data: { confirm: "Please Log In to Vote" } do %>
                <button class="btn btn-danger">
                  <i class="fas fa-thumbs-down" style="color:white"></i>
                  <span class="ncount-<%= offer.id %>" style="color:white"> (<%= offer.get_downvotes.size %>)</span>
                </button>
              <% end %>
          </div>
        <% end %>
        </div><!--close div for to likes and dislikes -->
      </div><!--div close card body-->
    </div> <!--div class="card border-secondary mb-3" id="reviewsIndexCard"-->
  <hr>   
  <% end %>
</div><!--div class="container emp-profile"-->

app/views/offers/downvote.js.erb
$('.ncount-<%= @offer.id %>').html(' (<%=escape_javascript @offer.get_downvotes.size.to_s %>)');
$('.vcount-<%= @offer.id %>').html(' (<%=escape_javascript @offer.get_upvotes.size.to_s %>)');

app/views/offers/edit.html.erb
<% content_for :title do %>
 Edit Review | RelyApply
<% end %>

<h1 style="color: white">Editing Your Interview Review</h1>
  <% if user_signed_in? && current_user.id == @offer.user_id %>
	<%= render 'form', offer: @offer %>
  <% else %> 
    <% controller.redirect_to root_path %>
  <% end %>
</div>

app/views/offers/index.html.erb
<% content_for :title do %>
  Interview Reviews | RelyApply
<% end %>

<% if mobile_device == ("mobile" or "tablet") %>
  <%= render 'offer_index_mobile'%>
<% else %>
  <%= render 'offer_index_desktop'%>
<% end %>

app/views/offers/new.html.erb
<% content_for :title do %>
 New Review | RelyApply
<% end %>

<h3 style="color:white;">New Review for <%= @company.name %></h3>
<% if user_signed_in? %>
  <%= render 'new_offer_form', offer: @offer %>
<% else %>
  <div>
	<h4> You need to <%= link_to "Log in", new_user_session_path %> or <%= link_to "Sign up", new_user_registration_path %> to request for information changes on <%= @company.name%>'s profile </h4>
  </div>
<% end %>

app/views/offers/show.html.erb
<% controller.redirect_to root_path %>

app/views/offers/upvote.js.erb
$('.vcount-<%= @offer.id %>').html(' (<%=escape_javascript @offer.get_upvotes.size.to_s %>)');
$('.ncount-<%= @offer.id %>').html(' (<%=escape_javascript @offer.get_downvotes.size.to_s %>)');