config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :contacts, only: [:new, :create, :index]
  resources :requests
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :pages
  resources :flags
  resources :reviews do
   member do
    get "like", to: "reviews#upvote"
    get "dislike", to: "reviews#downvote"
   end
  end
  
  resources :offers do
   member do
    get "like", to: "offers#upvote"
    get "dislike", to: "offers#downvote"
   end
  end
  
  resources :offers do 
     resources :companies
  end
  
  resources :reviews do 
    resources :companies
    resources :flags
  end 
  
  resources :flags do
    resources :reviews
  end
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' } 
 
  
  resources :users, only: [:show]

  resources :companies do 
  	resources :reviews
  	 collection do 
  	 	get :search #creates new path for the search input
  	  get :autocomplete
     end
    resources :offers
     collection do 
      get :search #creates new path for the search input
     end
    resources :requests
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'companies#index'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tos', to: 'pages#tos'
  get 'privacy', to: 'pages#privacy'
  get 'profile', to: 'users#show'
  get 'testing', to: 'pages#testing'
  get 'faq', to: 'pages#faq'

  match 'users/:id' => 'users#show', via: :get

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  load_and_authorize_resource
  before_action :set_review, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :vote]
  before_action :company_friendly_params, only: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :limit_review, only: [:new, :create]
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.where(company_id: params[:company_id]) 
    if params[:search].present?
      @q = @company.reviews.near(params[:search], 200, :order => 'distance' ).ransack(params[:q])
      @reviews = @q.result(:distinct => true)
    else 
      @q = @company.reviews.ransack(params[:q])
      @reviews = @q.result(:distinct => true)
    end
  end


  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = @company.reviews.new(review_params)
    @review.user = current_user
    respond_to do |format|
      if @review.save
        format.html { redirect_to @company, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html {  redirect_to @review.user, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: 'Review was successfully deleted.' }
      format.json { head :no_content }
    end
  end
      
  def upvote
    if !current_user.liked? @review
      @review.upvote_by current_user
    elsif current_user.liked? @review
      @review.unliked_by current_user
    else current_user.liked? @review
      redirect_back fallback_location: root_path
    end
      respond_to do |format|
        format.html { redirect_back fallback_location: root_path }
        format.json { render json: { count: @review.upvoted_count } }
        format.js { render layout: false }
      end
  end

  def downvote
    if !current_user.disliked? @review
      @review.downvote_by current_user
    elsif current_user.disliked? @review
      @review.undisliked_by current_user
    end
     respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { render json: { count: @review.downvoted_count } }
      format.js { render layout: false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id].to_i)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:review_id, :position, :employment_type, :satisfaction, :responsiveness, :company_id, :user_id,:response_time, :application_type, :experience, :street_number, :company_id, :address, :locality, :route, :administrative_area_level_1, :country, :postal_code)
    end

    def company_friendly_params
       @company = Company.friendly.find(params[:company_id])
    end 

    def limit_review
      user_review = current_user.company_review(@company)

      if user_review.present? 
        redirect_to proc { company_path(@company) }, alert: "You have already submitted a post-application review to this company. You can resubmit a new review to this company every quarter of the year." unless current_user.admin?
        #RedirectToAction("companies","show", alert: "You have already submitted a post-application review to this company. You can resubmit a new review to this company every quarter of the year."
      end
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_review_index_desktop.html.erb
<div class="container emp-profile">
  <div class="well" id="wellProfileForReviewIndex">
    <div id= "headerProfileForReviewIndex">  
      <h3><%=@company.name%>'s </strong>Application Reviews<strong></h3>
    </div>
  </div><!-- div class="well" id="wellProfileForReviewIndex"-->
  <p>Want to add a review? Go back to <%= link_to @company.name, company_path(@company), method: :get%>'s profile and click "Submit Review"</p>
  <p>
  <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Reminder!
  </a>
    <div class="collapse" id="collapseExample">
      <div class="text-left">
        <div class="alert alert-info" role="alert">
          <ul>
            <li><h6>The information below is based on what users have submitted in their reviews</li>
            <li><h6>Their opinions are based on what they felt was a proper follow-up after an application or an interview</h6></li>
            <li><h6>If you don't hear back within a reasonable time frame relative to the other reviews, it is highly suggested you do a follow-up or assume you didn't qualify for the job.</h6></li>
          </ul>
        </div>
      </div>
    </div>
  <hr id="reviewIndexHr">
    <div class="container-fluid">
    <%= search_form_for @q, url: company_reviews_path(params[:company_id]) do |f| %> 
      <!-- end of collapse section -->
        <div class="row">
          <h4 class="col"><strong>Filter & Search</strong></h4>
        </div>
        <div class="row">
           <div class="col-sm">
            <%= f.label :response_time_eq, "Response Time: " %>
            <%= f.select :response_time_eq, options_for_select([
              ["Less than a week","Less than a week"],
              ["1-2 weeks","1-2 weeks"],
              ["2-3 weeks","2-3 weeks"],
              ["3-4 weeks","3-4 weeks"],
              ["Not within a month", "Not within a month"]
              ] , @q.response_time_eq), prompt: '--Select--' %>
          </div>
          <div class="col-sm">
            <%= f.label :position, "Position:" %>
            <%= h f.search_field :position_cont, :placeholder => 'Search Position'%>
          </div>
        </div>
        <div class="row">
          <div class="col-sm">
            <%= f.label :responsiveness_eq, "Applicant Satisfied:" %>
            <%= f.select :responsiveness_eq, options_for_select([
              ["Yes","Yes"],
              ["No","No"]
              ] , @q.responsiveness_eq), prompt: '--Select--'   %>
          </div>
          <div class="col-sm">
            <%= f.label :employment_type_eq, "Employment Type: " %>
            <%= f.select :employment_type_eq, options_for_select([
              ["Full-Time","Full-Time"],
              ["Part-Time","Part-Time"],
              ["Intern","Intern"],
              ["Temporary","Temporary"],
              ["Contractor","Contractor"]
              ] , @q.employment_type_eq), prompt: '--Select--'  %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm">
           <%= f.label :application_type_eq, "Application Type: " %>
           <%= f.select :application_type_eq, options_for_select([
              ["Online","Online"],
              ["In-person","In-person"],
              ["Referral","Referral"]
              ] , @q.employment_type_eq), prompt: '--Select--'  %>
          </div>
          <div class="col-sm">
            <%= f.label :Location, "Location: " %>
            <%= h text_field_tag :search, params[:search], :placeholder => '[City, State] or Zip Code'%>
          </div>
        </div>
        <div class="row">
          <div class="col-sm">
           <%= f.label :experience, "Experience: " %>
           <%= f.select :experience, options_for_select([["Equal or Greater","Equal or Greater"], ["Moderately less experience","Moderately less experience"], ["Little to no experience","Little to no experience"]], @q.experience), prompt: '--Select--' %>
          </div>
        </div>
        <br />
        <div colspan="1" align="center">
          <%= f.submit :class => "btn btn-primary" %>  <a href="<%=company_reviews_path%>" class="btn btn-primary" color="black">Clear filters</a>
        <div>
      <% end %>
    </div> <!--div class="container-fluid"-->
  </div><!--textleft -->
  <hr id="reviewIndexHr">
  <div>
  <h2><strong>Total Reviews: <%= @company.reviews.size %></strong></h2>
      <div class="text-left" colspan="1" style="display: inline">  
          <strong>Sort By: </strong>
      </div>
      <div class="text-left" colspan="1" style="display: inline">
        <%= sort_link(@q, :created_at, default_order: :asc) do %>
          <strong>Date</strong>
        <% end %>
      </div>
      <div class="text-left" colspan="1" style="display: inline">  
          <strong>|</strong>
      </div>
      <div class="text-right" colspan="1" style="display: inline" >
        <%= sort_link(@q, :cached_votes_up, default_order: :desc) do %>
          <strong>Likes</strong>
        <% end %>
      </div>    
  </div>
  <% @reviews.each do |review| %>
    <div class="card border-secondary mb-3" id="reviewsIndexCard">
      <div class="card-header" id="reviewsIndexCardHeader">
        <h3>Response Time: <%= review.response_time %></h3>
      </div>
      <div class="card-body" id="cardBodyText">
        <p style="color:grey !important;"><I>Review Submitted: <%= review.created_at.strftime("%B %d, %Y") %></I></p>
         <h5><strong>Responsiveness</strong></h5>
         <div class="row"><!--first row of card-->
          <div class="col-md-6" >
            <p><strong>Were you satisfied with their level of responsiveness?</strong> </p>
          </div>
          <div class="col-md-6" >
            <p><%= review.responsiveness %></p>
          </div>
        </div>
        <hr>
        <h5><strong>Application Details</strong></h5>
        <div class="row"><!--first row of card-->
          <div class="col-md-6">
            <% if review.position.blank? %> 
              <p><strong>Position:</strong> n/a </p>
            <% else %>
              <p><strong>Position:</strong> <%= review.position %> </p>
            <% end %>
          </div>
          <div class="col-md-6">
            <% if review.employment_type.blank? %> 
              <p><strong>Employment Type:</strong> n/a</p>
            <% else %>
              <p><strong>Employment Type:</strong> <%= review.employment_type %></p>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <% if review.application_type.blank? %> 
             <p><strong>Application Type:</strong> n/a</p>
            <% else %>
              <p><strong>Application Type:</strong> <%= review.application_type %></p>
            <% end %>
          </div>
          <div class="col-md-6">
            <% if review.experience.blank? %> 
              <p><strong>Experience Relative to Job Requirement:</strong> n/a </p>
            <% else %>
              <p><strong>Experience Relative to Job Requirement:</strong> <%= review.experience %> </p>
            <% end %>
          </div>
        </div>
        <div class="row"> <!--second row of card-->
            <div class="col-md-6">
              <% if review.address.blank? %> 
                <p><strong>Location:</strong> n/a</p>
              <% else %>
                <p><strong>Location:</strong> <%= review.address.chomp(', USA') %></p>
              <% end %>                 
            </div>
        </div>
        <% if user_signed_in? %>

          <div colspan="1" class="vote-count bind-<%= review.id %>" style="text-align: center"> <!--links to likes and dislikes -->
            <%= link_to like_review_path(review),:remote => true, method: :get, class: "vpos", id: "thumbs"  do %>
                <button class="btn btn-success">
                  <i class="fas fa-thumbs-up" style="color:white"></i>
                  <span class="vcount-<%= review.id %>" style="color:white"> (<%= review.get_upvotes.size %>)</span>
                </button>
            <% end %>
            <%= link_to dislike_review_path(review),:remote => true, method: :get, class: "vneg", id: "thumbs" do %>
                <button class="btn btn-danger">
                  <i class="fas fa-thumbs-down" style="color:white"></i>
                  <span class="ncount-<%= review.id %>" style="color:white"> (<%= review.get_downvotes.size %>)</span>
                </button>
            <% end %>
        <% else %>
          <div colspan="1" style="text-align: center"> <!--links to likes and dislikes -->
              <%= link_to new_user_session_path, data: { confirm: "Please Log In to Vote" } do %>
                <button class="btn btn-success">
                  <i class="fas fa-thumbs-up" style="color:white"></i>
                  <span class="vcount-<%= review.id %>" style="color:white"> (<%= review.get_upvotes.size %>)</span>
                </button>
              <% end %>
              <%= link_to new_user_session_path, data: { confirm: "Please Log In to Vote" } do %>
                <button class="btn btn-danger">
                  <i class="fas fa-thumbs-down" style="color:white"></i>
                  <span class="ncount-<%= review.id %>" style="color:white"> (<%= review.get_downvotes.size %>)</span>
                </button>
              <% end %>
        <% end %>
        </div><!--close div for to likes and dislikes -->
      </div><!--div close card body-->
    </div> 
    <hr>   
  <% end %>
</div><!--div class="container emp-profile"-->

app/views/reviews/_review_index_mobile.html.erb
<div style="background-color: white; padding: 10px;">
  <div class="well" id="wellProfileForReviewIndex">
    <div id= "headerProfileForReviewIndex">  
      <h3><%=@company.name%>'s </strong>Application Reviews<strong></h3>
    </div>
  </div><!-- div class="well" id="wellProfileForReviewIndex"-->
  <p>Want to add a review? Go back to <%= link_to @company.name, company_path(@company), method: :get%>'s profile and click "Submit Review"</p>
  <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Reminder!
  </a>
	<div class="collapse" id="collapseExample">
	  <div class="text-left">
	    <div class="alert alert-info" role="alert">
	      <ul>
	        <li><h6>The information below is based on what users have submitted in their reviews</li>
	        <li><h6>Their opinions are based on what they felt was a proper follow-up after an application or an interview</h6></li>
	        <li><h6>If you don't hear back within a reasonable time frame relative to the other reviews, it is highly suggested you do a follow-up or assume you didn't qualify for the job.</h6></li>
	      </ul>
	    </div>
	  </div>
	</div>
  <hr id="reviewIndexHr">
  <%= search_form_for @q, url: company_reviews_path(params[:company_id]) do |f| %> 
	<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseSearch" aria-expanded="false" aria-controls="collapseSearch" style="width: 100%;">
   Filter & Search
  </button>
	<div class="collapse" id="collapseSearch">
		<br />
	    <div class="row">
	      <div class="col-sm">
	        <%= f.label :response_time_eq, "Response Time: " %>
	        <%= f.select :response_time_eq, options_for_select([
	          ["Less than a week","Less than a week"],
	          ["1-2 weeks","1-2 weeks"],
	          ["2-3 weeks","2-3 weeks"],
	          ["3-4 weeks","3-4 weeks"],
	          ["Not within a month", "Not within a month"]
	          ] , @q.response_time_eq), prompt: '--Select--' %>
	      </div>
		    <div class="col-sm">
          <%= f.label :responsiveness_eq, "Applicant Satisfied:" %>
          <%= f.select :responsiveness_eq, options_for_select([
            ["Yes","Yes"],
            ["No","No"]
            ] , @q.responsiveness_eq), prompt: '--Select--'   %>
        </div>          
      </div>
     	<div class="row">
        <div class="col-sm">
          <%= f.label :employment_type_eq, "Employment Type: " %>
          <%= f.select :employment_type_eq, options_for_select([
            ["Full-Time","Full-Time"],
            ["Part-Time","Part-Time"],
            ["Intern","Intern"],
            ["Temporary","Temporary"],
            ["Contractor","Contractor"]
            ] , @q.employment_type_eq), prompt: '--Select--'  %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm">
          <%= f.label :application_type_eq, "Application Type: " %>
          <%= f.select :application_type_eq, options_for_select([
            ["Online","Online"],
            ["In-person","In-person"],
            ["Referral","Referral"]
            ] , @q.employment_type_eq), prompt: '--Select--'  %>
        </div>
        <div class="col-sm">
          <%= f.label :experience, "Experience: " %>
          <%= f.select :experience, options_for_select([["Equal or Greater","Equal or Greater"], ["Moderately less experience","Moderately less experience"], ["Little to no experience","Little to no experience"]], @q.experience), prompt: '--Select--' %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm" id="locationFieldMobile">
          <%= f.label :Location, "Location: " %>
          <%= h text_field_tag :search, params[:search], :placeholder => '[City, State] or Zip Code', :class => 'form-control'%>
        </div>
      </div>
      <br/>
      <div class="row">
        <div class="col-sm">
          <%= f.label :position, "Position:" %>
          <%= h f.search_field :position_cont, :placeholder => 'Search Position', :class => 'form-control'%>
        </div>
      </div>
      <br />
      <div colspan="1" align="center">
        <%= f.submit :class => "btn btn-primary" %>  <a href="<%=company_reviews_path%>" class="btn btn-primary" color="black">Clear filters</a>
      </div>
      <% end %>
  </div><!--div class="collapse" id="collapseSearch"-->
  <hr id="reviewIndexHr">
  <div>
    <h2><strong>Total Reviews: <%= @company.reviews.size %></strong></h2>
    <div class="text-left" colspan="1" style="display: inline">  
      <strong>Sort By: </strong>
    </div>
    <div class="text-left" colspan="1" style="display: inline">
      <%= sort_link(@q, :created_at, default_order: :asc) do %>
        <strong>Date</strong>
      <% end %>
    </div>
    <div class="text-left" colspan="1" style="display: inline">  
        <strong>|</strong>
    </div>
    <div class="text-right" colspan="1" style="display: inline" >
      <%= sort_link(@q, :cached_votes_up, default_order: :desc) do %>
        <strong>Likes</strong>
      <% end %>
    </div>    
  </div>
  <% @reviews.each do |review| %>
    <div>
      <div class="card-header" id="reviewsIndexCardHeader">
        <h5 style="color:white;">Response Time: <%= review.response_time %></h5>   
      </div>
      <div class="card-body" id="cardBodyText" style="padding-left: 5px; border: 1px grey solid; width: 100%;">
        <p style="color:grey !important;"><I>Review Submitted: <%= review.created_at.strftime("%B %d, %Y") %></I></p>
         <h5><strong>Responsiveness</strong></h5>
         <div class="row"><!--first row of card-->
          <div class="col-md-6" >
            <p><strong>Were you satisfied with their level of responsiveness?</strong> </p>
          </div>
          <div class="col-md-6" >
            <p><%= review.responsiveness %></p>
          </div>
        </div>
        <hr>
        <h5><strong>Application Details</strong></h5>
        <div class="row"><!--first row of card-->
          <div class="col-md-6">
            <% if review.position.blank? %> 
              <p><strong>Position:</strong> n/a </p>
            <% else %>
              <p><strong>Position:</strong> <%= review.position %> </p>
            <% end %>
          </div>
          <div class="col-md-6">
            <% if review.employment_type.blank? %> 
              <p><strong>Employment Type:</strong> n/a</p>
            <% else %>
              <p><strong>Employment Type:</strong> <%= review.employment_type %></p>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <% if review.application_type.blank? %> 
             <p><strong>Application Type:</strong> n/a</p>
            <% else %>
              <p><strong>Application Type:</strong> <%= review.application_type %></p>
            <% end %>
          </div>
          <div class="col-md-6">
            <% if review.experience.blank? %> 
              <p><strong>Experience Relative to Job Requirement:</strong> n/a </p>
            <% else %>
              <p><strong>Experience Relative to Job Requirement:</strong> <%= review.experience %> </p>
            <% end %>
          </div>
        </div>
        <div class="row"> <!--second row of card-->
            <div class="col-md-6">
              <% if review.address.blank? %> 
                <p><strong>Location:</strong> n/a</p>
              <% else %>
                <p><strong>Location:</strong> <%= review.address.chomp(', USA') %></p>
              <% end %>                 
            </div>
        </div>
        <% if user_signed_in? %>
          <div colspan="1" class="vote-count bind-<%= review.id %>" style="text-align: center"> <!--links to likes and dislikes -->
            <%= link_to like_review_path(review),:remote => true, method: :get, class: "vpos", id: "thumbs"  do %>
                <button class="btn btn-success">
                  <i class="fas fa-thumbs-up" style="color:white"></i>
                  <span class="vcount-<%= review.id %>" style="color:white"> (<%= review.get_upvotes.size %>)</span>
                </button>
            <% end %>
            <%= link_to dislike_review_path(review),:remote => true, method: :get, class: "vneg", id: "thumbs" do %>
                <button class="btn btn-danger">
                  <i class="fas fa-thumbs-down" style="color:white"></i>
                  <span class="ncount-<%= review.id %>" style="color:white"> (<%= review.get_downvotes.size %>)</span>
                </button>
            <% end %>
        <% else %>
          <div colspan="1" style="text-align: center"> <!--links to likes and dislikes -->
            <%= link_to new_user_session_path, data: { confirm: "Please Log In to Vote" } do %>
              <button class="btn btn-success">
                <i class="fas fa-thumbs-up" style="color:white"></i>
                <span class="vcount-<%= review.id %>" style="color:white"> (<%= review.get_upvotes.size %>)</span>
              </button>
              <% end %>
              <%= link_to new_user_session_path, data: { confirm: "Please Log In to Vote" } do %>
                <button class="btn btn-danger">
                  <i class="fas fa-thumbs-down" style="color:white"></i>
                  <span class="ncount-<%= review.id %>" style="color:white"> (<%= review.get_downvotes.size %>)</span>
                </button>
              <% end %>
          </div><!--links to likes and dislikes -->
        <% end %>
        </div><!--close div for to likes and dislikes -->
      </div> 
    </div> <!--containerfluid-->
  <hr>   
  <% end %>
</div>

app/views/reviews/downvote.js.erb
$('.ncount-<%= @review.id %>').html(' (<%=escape_javascript @review.get_downvotes.size.to_s %>)');
$('.vcount-<%= @review.id %>').html(' (<%=escape_javascript @review.get_upvotes.size.to_s %>)');

app/views/reviews/edit.html.erb
<% content_for :title do %>
 Edit Review | RelyApply
<% end %>

<h1 style="color: white">Editing Your Application Review</h1>
<div>
  <% if user_signed_in? && current_user.id == @review.user_id %>
		<%= render 'form', review: @review %>
	<% else %> 
    <% controller.redirect_to root_path %>
	<% end %>
</div>

app/views/reviews/index.html.erb
<% content_for :title do %>
 Application Reviews | RelyApply
<% end %>

<% if mobile_device == ("mobile" or "tablet") %>
  <%= render 'review_index_mobile'%>
<% else %>
  <%= render 'review_index_desktop'%>
<% end %>

app/views/reviews/new.html.erb
<% content_for :title do %>
 New Review | RelyApply
<% end %>

<h3 style="color:white">New Review for <%= @company.name %></h3>
<% if user_signed_in?%> 
    <%= render 'new_review_form', review: @review %>
<% else %>
	<div>
	  <h4> You need to <%= link_to "Log in", new_user_session_path %> or <%= link_to "Sign up", new_user_registration_path %> to request for information changes on <%= @company.name%>'s profile </h4>
	</div>
<% end %>

app/views/reviews/show.html.erb
<% controller.redirect_to root_path %>

app/views/reviews/upvote.js.erb
$('.vcount-<%= @review.id %>').html(' (<%=escape_javascript @review.get_upvotes.size.to_s  %>)'); 
$('.ncount-<%= @review.id %>').html(' (<%=escape_javascript @review.get_downvotes.size.to_s %>)');